export {Navbar} from './inicio/Navbar'
export {About} from './inicio/About'
export {Header} from './inicio/Header'
export {Footer} from './inicio/Footer'
export {Courses} from './inicio/Courses'
export {Gallery} from './inicio/Gallery'
export {Testimonials} from './inicio/Testimonials'
export {LoginForm} from './intranet/LoginForm'
export {Sidebar} from './intranet/Sidebar'
export {Bienvenida} from './intranet/alumno/Bienvenida'
export {CourseSelector} from './intranet/alumno/CourseSelector'
export {CursoCard} from './intranet/alumno/CursoCard'
export {PromedioCard} from './intranet/alumno/PromedioCard'
export {NotasCard} from './intranet/alumno/NotasCard'
export {CuotasCard} from './intranet/alumno/CuotasCard'
export {AsistenciaCard} from './intranet/alumno/AsistenciaCard'
export {ContextStrip} from './intranet/alumno/ContextStrip'
export {PanelContent} from './intranet/alumno/PanelContent'
export {TableAlumnos} from './intranet/admin/alumnos/TableAlumnos'
export {TableCursos} from './intranet/admin/cursos/TableCursos'
export {TableSecciones} from './intranet/admin/secciones/TableSecciones'
export {default as SectionDetail} from './intranet/admin/secciones/SectionDetail'
export {default as AlumnoDetail} from './intranet/admin/alumnos/AlumnoDetail'
export {default as ConstanciaConfigurator} from './intranet/admin/constancia/ConstanciaConfigurator'